// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "lotto-journal/api/internal/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DrawRepositoryInterface is an autogenerated mock type for the DrawRepositoryInterface type
type DrawRepositoryInterface struct {
	mock.Mock
}

// FindByDate provides a mock function with given fields: date
func (_m *DrawRepositoryInterface) FindByDate(date time.Time) (*models.Draw, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for FindByDate")
	}

	var r0 *models.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time) (*models.Draw, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(time.Time) *models.Draw); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Draw)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindNextDraw provides a mock function with given fields: fromDate
func (_m *DrawRepositoryInterface) FindNextDraw(fromDate time.Time) (*models.Draw, error) {
	ret := _m.Called(fromDate)

	if len(ret) == 0 {
		panic("no return value specified for FindNextDraw")
	}

	var r0 *models.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time) (*models.Draw, error)); ok {
		return rf(fromDate)
	}
	if rf, ok := ret.Get(0).(func(time.Time) *models.Draw); ok {
		r0 = rf(fromDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Draw)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(fromDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOrCreate provides a mock function with given fields: date
func (_m *DrawRepositoryInterface) FindOrCreate(date time.Time) (*models.Draw, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 *models.Draw
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time) (*models.Draw, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(time.Time) *models.Draw); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Draw)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDrawRepositoryInterface creates a new instance of DrawRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDrawRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DrawRepositoryInterface {
	mock := &DrawRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
