// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"lotto-journal/api/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockDrawResultRepositoryInterface creates a new instance of MockDrawResultRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDrawResultRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDrawResultRepositoryInterface {
	mock := &MockDrawResultRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDrawResultRepositoryInterface is an autogenerated mock type for the DrawResultRepositoryInterface type
type MockDrawResultRepositoryInterface struct {
	mock.Mock
}

type MockDrawResultRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDrawResultRepositoryInterface) EXPECT() *MockDrawResultRepositoryInterface_Expecter {
	return &MockDrawResultRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CreateInBatches provides a mock function for the type MockDrawResultRepositoryInterface
func (_mock *MockDrawResultRepositoryInterface) CreateInBatches(results []*models.DrawResult) error {
	ret := _mock.Called(results)

	if len(ret) == 0 {
		panic("no return value specified for CreateInBatches")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*models.DrawResult) error); ok {
		r0 = returnFunc(results)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDrawResultRepositoryInterface_CreateInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInBatches'
type MockDrawResultRepositoryInterface_CreateInBatches_Call struct {
	*mock.Call
}

// CreateInBatches is a helper method to define mock.On call
//   - results []*models.DrawResult
func (_e *MockDrawResultRepositoryInterface_Expecter) CreateInBatches(results any) *MockDrawResultRepositoryInterface_CreateInBatches_Call {
	return &MockDrawResultRepositoryInterface_CreateInBatches_Call{Call: _e.mock.On("CreateInBatches", results)}
}

func (_c *MockDrawResultRepositoryInterface_CreateInBatches_Call) Run(run func(results []*models.DrawResult)) *MockDrawResultRepositoryInterface_CreateInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.DrawResult
		if args[0] != nil {
			arg0 = args[0].([]*models.DrawResult)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDrawResultRepositoryInterface_CreateInBatches_Call) Return(err error) *MockDrawResultRepositoryInterface_CreateInBatches_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDrawResultRepositoryInterface_CreateInBatches_Call) RunAndReturn(run func(results []*models.DrawResult) error) *MockDrawResultRepositoryInterface_CreateInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInBatchesInTransaction provides a mock function for the type MockDrawResultRepositoryInterface
func (_mock *MockDrawResultRepositoryInterface) CreateInBatchesInTransaction(tx *gorm.DB, results []*models.DrawResult) error {
	ret := _mock.Called(tx, results)

	if len(ret) == 0 {
		panic("no return value specified for CreateInBatchesInTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, []*models.DrawResult) error); ok {
		r0 = returnFunc(tx, results)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDrawResultRepositoryInterface_CreateInBatchesInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInBatchesInTransaction'
type MockDrawResultRepositoryInterface_CreateInBatchesInTransaction_Call struct {
	*mock.Call
}

// CreateInBatchesInTransaction is a helper method to define mock.On call
//   - tx *gorm.DB
//   - results []*models.DrawResult
func (_e *MockDrawResultRepositoryInterface_Expecter) CreateInBatchesInTransaction(tx any, results any) *MockDrawResultRepositoryInterface_CreateInBatchesInTransaction_Call {
	return &MockDrawResultRepositoryInterface_CreateInBatchesInTransaction_Call{Call: _e.mock.On("CreateInBatchesInTransaction", tx, results)}
}

func (_c *MockDrawResultRepositoryInterface_CreateInBatchesInTransaction_Call) Run(run func(tx *gorm.DB, results []*models.DrawResult)) *MockDrawResultRepositoryInterface_CreateInBatchesInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 []*models.DrawResult
		if args[1] != nil {
			arg1 = args[1].([]*models.DrawResult)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDrawResultRepositoryInterface_CreateInBatchesInTransaction_Call) Return(err error) *MockDrawResultRepositoryInterface_CreateInBatchesInTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDrawResultRepositoryInterface_CreateInBatchesInTransaction_Call) RunAndReturn(run func(tx *gorm.DB, results []*models.DrawResult) error) *MockDrawResultRepositoryInterface_CreateInBatchesInTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByDrawIDInTransaction provides a mock function for the type MockDrawResultRepositoryInterface
func (_mock *MockDrawResultRepositoryInterface) DeleteByDrawIDInTransaction(tx *gorm.DB, drawID uuid.UUID) error {
	ret := _mock.Called(tx, drawID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByDrawIDInTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID) error); ok {
		r0 = returnFunc(tx, drawID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDrawResultRepositoryInterface_DeleteByDrawIDInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByDrawIDInTransaction'
type MockDrawResultRepositoryInterface_DeleteByDrawIDInTransaction_Call struct {
	*mock.Call
}

// DeleteByDrawIDInTransaction is a helper method to define mock.On call
//   - tx *gorm.DB
//   - drawID uuid.UUID
func (_e *MockDrawResultRepositoryInterface_Expecter) DeleteByDrawIDInTransaction(tx any, drawID any) *MockDrawResultRepositoryInterface_DeleteByDrawIDInTransaction_Call {
	return &MockDrawResultRepositoryInterface_DeleteByDrawIDInTransaction_Call{Call: _e.mock.On("DeleteByDrawIDInTransaction", tx, drawID)}
}

func (_c *MockDrawResultRepositoryInterface_DeleteByDrawIDInTransaction_Call) Run(run func(tx *gorm.DB, drawID uuid.UUID)) *MockDrawResultRepositoryInterface_DeleteByDrawIDInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDrawResultRepositoryInterface_DeleteByDrawIDInTransaction_Call) Return(err error) *MockDrawResultRepositoryInterface_DeleteByDrawIDInTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDrawResultRepositoryInterface_DeleteByDrawIDInTransaction_Call) RunAndReturn(run func(tx *gorm.DB, drawID uuid.UUID) error) *MockDrawResultRepositoryInterface_DeleteByDrawIDInTransaction_Call {
	_c.Call.Return(run)
	return _c
}
