// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"lotto-journal/api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserServiceInterface creates a new instance of MockUserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type MockUserServiceInterface struct {
	mock.Mock
}

type MockUserServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceInterface) EXPECT() *MockUserServiceInterface_Expecter {
	return &MockUserServiceInterface_Expecter{mock: &_m.Mock}
}

// Deactivate provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) Deactivate(lineUserID string) error {
	ret := _mock.Called(lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(lineUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserServiceInterface_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockUserServiceInterface_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - lineUserID string
func (_e *MockUserServiceInterface_Expecter) Deactivate(lineUserID any) *MockUserServiceInterface_Deactivate_Call {
	return &MockUserServiceInterface_Deactivate_Call{Call: _e.mock.On("Deactivate", lineUserID)}
}

func (_c *MockUserServiceInterface_Deactivate_Call) Run(run func(lineUserID string)) *MockUserServiceInterface_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_Deactivate_Call) Return(err error) *MockUserServiceInterface_Deactivate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserServiceInterface_Deactivate_Call) RunAndReturn(run func(lineUserID string) error) *MockUserServiceInterface_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreate provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) FindOrCreate(lineUserID string) (*models.User, bool, error) {
	ret := _mock.Called(lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 *models.User
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.User, bool, error)); ok {
		return returnFunc(lineUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = returnFunc(lineUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(lineUserID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(lineUserID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserServiceInterface_FindOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreate'
type MockUserServiceInterface_FindOrCreate_Call struct {
	*mock.Call
}

// FindOrCreate is a helper method to define mock.On call
//   - lineUserID string
func (_e *MockUserServiceInterface_Expecter) FindOrCreate(lineUserID any) *MockUserServiceInterface_FindOrCreate_Call {
	return &MockUserServiceInterface_FindOrCreate_Call{Call: _e.mock.On("FindOrCreate", lineUserID)}
}

func (_c *MockUserServiceInterface_FindOrCreate_Call) Run(run func(lineUserID string)) *MockUserServiceInterface_FindOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_FindOrCreate_Call) Return(user *models.User, b bool, err error) *MockUserServiceInterface_FindOrCreate_Call {
	_c.Call.Return(user, b, err)
	return _c
}

func (_c *MockUserServiceInterface_FindOrCreate_Call) RunAndReturn(run func(lineUserID string) (*models.User, bool, error)) *MockUserServiceInterface_FindOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// Reactivate provides a mock function for the type MockUserServiceInterface
func (_mock *MockUserServiceInterface) Reactivate(lineUserID string) error {
	ret := _mock.Called(lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for Reactivate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(lineUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserServiceInterface_Reactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reactivate'
type MockUserServiceInterface_Reactivate_Call struct {
	*mock.Call
}

// Reactivate is a helper method to define mock.On call
//   - lineUserID string
func (_e *MockUserServiceInterface_Expecter) Reactivate(lineUserID any) *MockUserServiceInterface_Reactivate_Call {
	return &MockUserServiceInterface_Reactivate_Call{Call: _e.mock.On("Reactivate", lineUserID)}
}

func (_c *MockUserServiceInterface_Reactivate_Call) Run(run func(lineUserID string)) *MockUserServiceInterface_Reactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserServiceInterface_Reactivate_Call) Return(err error) *MockUserServiceInterface_Reactivate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserServiceInterface_Reactivate_Call) RunAndReturn(run func(lineUserID string) error) *MockUserServiceInterface_Reactivate_Call {
	_c.Call.Return(run)
	return _c
}
