// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"lotto-journal/api/internal/models"
	"lotto-journal/api/internal/repository"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockUserWinningRepositoryInterface creates a new instance of MockUserWinningRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserWinningRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserWinningRepositoryInterface {
	mock := &MockUserWinningRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserWinningRepositoryInterface is an autogenerated mock type for the UserWinningRepositoryInterface type
type MockUserWinningRepositoryInterface struct {
	mock.Mock
}

type MockUserWinningRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserWinningRepositoryInterface) EXPECT() *MockUserWinningRepositoryInterface_Expecter {
	return &MockUserWinningRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CreateInBatches provides a mock function for the type MockUserWinningRepositoryInterface
func (_mock *MockUserWinningRepositoryInterface) CreateInBatches(winnings []*models.UserWinning) error {
	ret := _mock.Called(winnings)

	if len(ret) == 0 {
		panic("no return value specified for CreateInBatches")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*models.UserWinning) error); ok {
		r0 = returnFunc(winnings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserWinningRepositoryInterface_CreateInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInBatches'
type MockUserWinningRepositoryInterface_CreateInBatches_Call struct {
	*mock.Call
}

// CreateInBatches is a helper method to define mock.On call
//   - winnings []*models.UserWinning
func (_e *MockUserWinningRepositoryInterface_Expecter) CreateInBatches(winnings any) *MockUserWinningRepositoryInterface_CreateInBatches_Call {
	return &MockUserWinningRepositoryInterface_CreateInBatches_Call{Call: _e.mock.On("CreateInBatches", winnings)}
}

func (_c *MockUserWinningRepositoryInterface_CreateInBatches_Call) Run(run func(winnings []*models.UserWinning)) *MockUserWinningRepositoryInterface_CreateInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.UserWinning
		if args[0] != nil {
			arg0 = args[0].([]*models.UserWinning)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserWinningRepositoryInterface_CreateInBatches_Call) Return(err error) *MockUserWinningRepositoryInterface_CreateInBatches_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserWinningRepositoryInterface_CreateInBatches_Call) RunAndReturn(run func(winnings []*models.UserWinning) error) *MockUserWinningRepositoryInterface_CreateInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInBatchesInTransaction provides a mock function for the type MockUserWinningRepositoryInterface
func (_mock *MockUserWinningRepositoryInterface) CreateInBatchesInTransaction(tx *gorm.DB, winnings []*models.UserWinning) error {
	ret := _mock.Called(tx, winnings)

	if len(ret) == 0 {
		panic("no return value specified for CreateInBatchesInTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, []*models.UserWinning) error); ok {
		r0 = returnFunc(tx, winnings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserWinningRepositoryInterface_CreateInBatchesInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInBatchesInTransaction'
type MockUserWinningRepositoryInterface_CreateInBatchesInTransaction_Call struct {
	*mock.Call
}

// CreateInBatchesInTransaction is a helper method to define mock.On call
//   - tx *gorm.DB
//   - winnings []*models.UserWinning
func (_e *MockUserWinningRepositoryInterface_Expecter) CreateInBatchesInTransaction(tx any, winnings any) *MockUserWinningRepositoryInterface_CreateInBatchesInTransaction_Call {
	return &MockUserWinningRepositoryInterface_CreateInBatchesInTransaction_Call{Call: _e.mock.On("CreateInBatchesInTransaction", tx, winnings)}
}

func (_c *MockUserWinningRepositoryInterface_CreateInBatchesInTransaction_Call) Run(run func(tx *gorm.DB, winnings []*models.UserWinning)) *MockUserWinningRepositoryInterface_CreateInBatchesInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 []*models.UserWinning
		if args[1] != nil {
			arg1 = args[1].([]*models.UserWinning)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserWinningRepositoryInterface_CreateInBatchesInTransaction_Call) Return(err error) *MockUserWinningRepositoryInterface_CreateInBatchesInTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserWinningRepositoryInterface_CreateInBatchesInTransaction_Call) RunAndReturn(run func(tx *gorm.DB, winnings []*models.UserWinning) error) *MockUserWinningRepositoryInterface_CreateInBatchesInTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByDrawIDInTransaction provides a mock function for the type MockUserWinningRepositoryInterface
func (_mock *MockUserWinningRepositoryInterface) DeleteByDrawIDInTransaction(tx *gorm.DB, drawID uuid.UUID) error {
	ret := _mock.Called(tx, drawID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByDrawIDInTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID) error); ok {
		r0 = returnFunc(tx, drawID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserWinningRepositoryInterface_DeleteByDrawIDInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByDrawIDInTransaction'
type MockUserWinningRepositoryInterface_DeleteByDrawIDInTransaction_Call struct {
	*mock.Call
}

// DeleteByDrawIDInTransaction is a helper method to define mock.On call
//   - tx *gorm.DB
//   - drawID uuid.UUID
func (_e *MockUserWinningRepositoryInterface_Expecter) DeleteByDrawIDInTransaction(tx any, drawID any) *MockUserWinningRepositoryInterface_DeleteByDrawIDInTransaction_Call {
	return &MockUserWinningRepositoryInterface_DeleteByDrawIDInTransaction_Call{Call: _e.mock.On("DeleteByDrawIDInTransaction", tx, drawID)}
}

func (_c *MockUserWinningRepositoryInterface_DeleteByDrawIDInTransaction_Call) Run(run func(tx *gorm.DB, drawID uuid.UUID)) *MockUserWinningRepositoryInterface_DeleteByDrawIDInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserWinningRepositoryInterface_DeleteByDrawIDInTransaction_Call) Return(err error) *MockUserWinningRepositoryInterface_DeleteByDrawIDInTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserWinningRepositoryInterface_DeleteByDrawIDInTransaction_Call) RunAndReturn(run func(tx *gorm.DB, drawID uuid.UUID) error) *MockUserWinningRepositoryInterface_DeleteByDrawIDInTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// FindDrawWinnings provides a mock function for the type MockUserWinningRepositoryInterface
func (_mock *MockUserWinningRepositoryInterface) FindDrawWinnings(drawID uuid.UUID) ([]repository.DrawWinningDetail, error) {
	ret := _mock.Called(drawID)

	if len(ret) == 0 {
		panic("no return value specified for FindDrawWinnings")
	}

	var r0 []repository.DrawWinningDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]repository.DrawWinningDetail, error)); ok {
		return returnFunc(drawID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []repository.DrawWinningDetail); ok {
		r0 = returnFunc(drawID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DrawWinningDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(drawID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserWinningRepositoryInterface_FindDrawWinnings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDrawWinnings'
type MockUserWinningRepositoryInterface_FindDrawWinnings_Call struct {
	*mock.Call
}

// FindDrawWinnings is a helper method to define mock.On call
//   - drawID uuid.UUID
func (_e *MockUserWinningRepositoryInterface_Expecter) FindDrawWinnings(drawID any) *MockUserWinningRepositoryInterface_FindDrawWinnings_Call {
	return &MockUserWinningRepositoryInterface_FindDrawWinnings_Call{Call: _e.mock.On("FindDrawWinnings", drawID)}
}

func (_c *MockUserWinningRepositoryInterface_FindDrawWinnings_Call) Run(run func(drawID uuid.UUID)) *MockUserWinningRepositoryInterface_FindDrawWinnings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserWinningRepositoryInterface_FindDrawWinnings_Call) Return(drawWinningDetails []repository.DrawWinningDetail, err error) *MockUserWinningRepositoryInterface_FindDrawWinnings_Call {
	_c.Call.Return(drawWinningDetails, err)
	return _c
}

func (_c *MockUserWinningRepositoryInterface_FindDrawWinnings_Call) RunAndReturn(run func(drawID uuid.UUID) ([]repository.DrawWinningDetail, error)) *MockUserWinningRepositoryInterface_FindDrawWinnings_Call {
	_c.Call.Return(run)
	return _c
}
