// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"lotto-journal/api/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTicketRepositoryInterface creates a new instance of MockTicketRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketRepositoryInterface {
	mock := &MockTicketRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTicketRepositoryInterface is an autogenerated mock type for the TicketRepositoryInterface type
type MockTicketRepositoryInterface struct {
	mock.Mock
}

type MockTicketRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketRepositoryInterface) EXPECT() *MockTicketRepositoryInterface_Expecter {
	return &MockTicketRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTicketRepositoryInterface
func (_mock *MockTicketRepositoryInterface) Create(ticket *models.Ticket) error {
	ret := _mock.Called(ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Ticket) error); ok {
		r0 = returnFunc(ticket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTicketRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ticket *models.Ticket
func (_e *MockTicketRepositoryInterface_Expecter) Create(ticket any) *MockTicketRepositoryInterface_Create_Call {
	return &MockTicketRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ticket)}
}

func (_c *MockTicketRepositoryInterface_Create_Call) Run(run func(ticket *models.Ticket)) *MockTicketRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Ticket
		if args[0] != nil {
			arg0 = args[0].(*models.Ticket)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTicketRepositoryInterface_Create_Call) Return(err error) *MockTicketRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepositoryInterface_Create_Call) RunAndReturn(run func(ticket *models.Ticket) error) *MockTicketRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindUnchecked provides a mock function for the type MockTicketRepositoryInterface
func (_mock *MockTicketRepositoryInterface) FindUnchecked(drawID uuid.UUID) ([]*models.Ticket, error) {
	ret := _mock.Called(drawID)

	if len(ret) == 0 {
		panic("no return value specified for FindUnchecked")
	}

	var r0 []*models.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]*models.Ticket, error)); ok {
		return returnFunc(drawID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []*models.Ticket); ok {
		r0 = returnFunc(drawID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(drawID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepositoryInterface_FindUnchecked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUnchecked'
type MockTicketRepositoryInterface_FindUnchecked_Call struct {
	*mock.Call
}

// FindUnchecked is a helper method to define mock.On call
//   - drawID uuid.UUID
func (_e *MockTicketRepositoryInterface_Expecter) FindUnchecked(drawID any) *MockTicketRepositoryInterface_FindUnchecked_Call {
	return &MockTicketRepositoryInterface_FindUnchecked_Call{Call: _e.mock.On("FindUnchecked", drawID)}
}

func (_c *MockTicketRepositoryInterface_FindUnchecked_Call) Run(run func(drawID uuid.UUID)) *MockTicketRepositoryInterface_FindUnchecked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTicketRepositoryInterface_FindUnchecked_Call) Return(tickets []*models.Ticket, err error) *MockTicketRepositoryInterface_FindUnchecked_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTicketRepositoryInterface_FindUnchecked_Call) RunAndReturn(run func(drawID uuid.UUID) ([]*models.Ticket, error)) *MockTicketRepositoryInterface_FindUnchecked_Call {
	_c.Call.Return(run)
	return _c
}

// FindUncheckedInTransaction provides a mock function for the type MockTicketRepositoryInterface
func (_mock *MockTicketRepositoryInterface) FindUncheckedInTransaction(tx *gorm.DB, drawID uuid.UUID) ([]*models.Ticket, error) {
	ret := _mock.Called(tx, drawID)

	if len(ret) == 0 {
		panic("no return value specified for FindUncheckedInTransaction")
	}

	var r0 []*models.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID) ([]*models.Ticket, error)); ok {
		return returnFunc(tx, drawID)
	}
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID) []*models.Ticket); ok {
		r0 = returnFunc(tx, drawID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*gorm.DB, uuid.UUID) error); ok {
		r1 = returnFunc(tx, drawID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepositoryInterface_FindUncheckedInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUncheckedInTransaction'
type MockTicketRepositoryInterface_FindUncheckedInTransaction_Call struct {
	*mock.Call
}

// FindUncheckedInTransaction is a helper method to define mock.On call
//   - tx *gorm.DB
//   - drawID uuid.UUID
func (_e *MockTicketRepositoryInterface_Expecter) FindUncheckedInTransaction(tx any, drawID any) *MockTicketRepositoryInterface_FindUncheckedInTransaction_Call {
	return &MockTicketRepositoryInterface_FindUncheckedInTransaction_Call{Call: _e.mock.On("FindUncheckedInTransaction", tx, drawID)}
}

func (_c *MockTicketRepositoryInterface_FindUncheckedInTransaction_Call) Run(run func(tx *gorm.DB, drawID uuid.UUID)) *MockTicketRepositoryInterface_FindUncheckedInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepositoryInterface_FindUncheckedInTransaction_Call) Return(tickets []*models.Ticket, err error) *MockTicketRepositoryInterface_FindUncheckedInTransaction_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTicketRepositoryInterface_FindUncheckedInTransaction_Call) RunAndReturn(run func(tx *gorm.DB, drawID uuid.UUID) ([]*models.Ticket, error)) *MockTicketRepositoryInterface_FindUncheckedInTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTicketRepositoryInterface
func (_mock *MockTicketRepositoryInterface) List(drawID uuid.UUID, userID uuid.UUID) ([]*models.Ticket, error) {
	ret := _mock.Called(drawID, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) ([]*models.Ticket, error)); ok {
		return returnFunc(drawID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) []*models.Ticket); ok {
		r0 = returnFunc(drawID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(drawID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTicketRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - drawID uuid.UUID
//   - userID uuid.UUID
func (_e *MockTicketRepositoryInterface_Expecter) List(drawID any, userID any) *MockTicketRepositoryInterface_List_Call {
	return &MockTicketRepositoryInterface_List_Call{Call: _e.mock.On("List", drawID, userID)}
}

func (_c *MockTicketRepositoryInterface_List_Call) Run(run func(drawID uuid.UUID, userID uuid.UUID)) *MockTicketRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepositoryInterface_List_Call) Return(tickets []*models.Ticket, err error) *MockTicketRepositoryInterface_List_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTicketRepositoryInterface_List_Call) RunAndReturn(run func(drawID uuid.UUID, userID uuid.UUID) ([]*models.Ticket, error)) *MockTicketRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCheckedInTransaction provides a mock function for the type MockTicketRepositoryInterface
func (_mock *MockTicketRepositoryInterface) MarkCheckedInTransaction(tx *gorm.DB, ticketIDs []uuid.UUID) error {
	ret := _mock.Called(tx, ticketIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkCheckedInTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, []uuid.UUID) error); ok {
		r0 = returnFunc(tx, ticketIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepositoryInterface_MarkCheckedInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCheckedInTransaction'
type MockTicketRepositoryInterface_MarkCheckedInTransaction_Call struct {
	*mock.Call
}

// MarkCheckedInTransaction is a helper method to define mock.On call
//   - tx *gorm.DB
//   - ticketIDs []uuid.UUID
func (_e *MockTicketRepositoryInterface_Expecter) MarkCheckedInTransaction(tx any, ticketIDs any) *MockTicketRepositoryInterface_MarkCheckedInTransaction_Call {
	return &MockTicketRepositoryInterface_MarkCheckedInTransaction_Call{Call: _e.mock.On("MarkCheckedInTransaction", tx, ticketIDs)}
}

func (_c *MockTicketRepositoryInterface_MarkCheckedInTransaction_Call) Run(run func(tx *gorm.DB, ticketIDs []uuid.UUID)) *MockTicketRepositoryInterface_MarkCheckedInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepositoryInterface_MarkCheckedInTransaction_Call) Return(err error) *MockTicketRepositoryInterface_MarkCheckedInTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepositoryInterface_MarkCheckedInTransaction_Call) RunAndReturn(run func(tx *gorm.DB, ticketIDs []uuid.UUID) error) *MockTicketRepositoryInterface_MarkCheckedInTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ResetCheckedStatusByDrawIDInTransaction provides a mock function for the type MockTicketRepositoryInterface
func (_mock *MockTicketRepositoryInterface) ResetCheckedStatusByDrawIDInTransaction(tx *gorm.DB, drawID uuid.UUID) error {
	ret := _mock.Called(tx, drawID)

	if len(ret) == 0 {
		panic("no return value specified for ResetCheckedStatusByDrawIDInTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID) error); ok {
		r0 = returnFunc(tx, drawID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketRepositoryInterface_ResetCheckedStatusByDrawIDInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetCheckedStatusByDrawIDInTransaction'
type MockTicketRepositoryInterface_ResetCheckedStatusByDrawIDInTransaction_Call struct {
	*mock.Call
}

// ResetCheckedStatusByDrawIDInTransaction is a helper method to define mock.On call
//   - tx *gorm.DB
//   - drawID uuid.UUID
func (_e *MockTicketRepositoryInterface_Expecter) ResetCheckedStatusByDrawIDInTransaction(tx any, drawID any) *MockTicketRepositoryInterface_ResetCheckedStatusByDrawIDInTransaction_Call {
	return &MockTicketRepositoryInterface_ResetCheckedStatusByDrawIDInTransaction_Call{Call: _e.mock.On("ResetCheckedStatusByDrawIDInTransaction", tx, drawID)}
}

func (_c *MockTicketRepositoryInterface_ResetCheckedStatusByDrawIDInTransaction_Call) Run(run func(tx *gorm.DB, drawID uuid.UUID)) *MockTicketRepositoryInterface_ResetCheckedStatusByDrawIDInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketRepositoryInterface_ResetCheckedStatusByDrawIDInTransaction_Call) Return(err error) *MockTicketRepositoryInterface_ResetCheckedStatusByDrawIDInTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketRepositoryInterface_ResetCheckedStatusByDrawIDInTransaction_Call) RunAndReturn(run func(tx *gorm.DB, drawID uuid.UUID) error) *MockTicketRepositoryInterface_ResetCheckedStatusByDrawIDInTransaction_Call {
	_c.Call.Return(run)
	return _c
}
