// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"lotto-journal/api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepositoryInterface creates a new instance of MockUserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type MockUserRepositoryInterface struct {
	mock.Mock
}

type MockUserRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterface_Expecter {
	return &MockUserRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) Create(user *models.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *models.User
func (_e *MockUserRepositoryInterface_Expecter) Create(user any) *MockUserRepositoryInterface_Create_Call {
	return &MockUserRepositoryInterface_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockUserRepositoryInterface_Create_Call) Run(run func(user *models.User)) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.User
		if args[0] != nil {
			arg0 = args[0].(*models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) Return(err error) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) RunAndReturn(run func(user *models.User) error) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLineUserID provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) FindByLineUserID(lineUserID string) (*models.User, error) {
	ret := _mock.Called(lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindByLineUserID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.User, error)); ok {
		return returnFunc(lineUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = returnFunc(lineUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(lineUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryInterface_FindByLineUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLineUserID'
type MockUserRepositoryInterface_FindByLineUserID_Call struct {
	*mock.Call
}

// FindByLineUserID is a helper method to define mock.On call
//   - lineUserID string
func (_e *MockUserRepositoryInterface_Expecter) FindByLineUserID(lineUserID any) *MockUserRepositoryInterface_FindByLineUserID_Call {
	return &MockUserRepositoryInterface_FindByLineUserID_Call{Call: _e.mock.On("FindByLineUserID", lineUserID)}
}

func (_c *MockUserRepositoryInterface_FindByLineUserID_Call) Run(run func(lineUserID string)) *MockUserRepositoryInterface_FindByLineUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_FindByLineUserID_Call) Return(user *models.User, err error) *MockUserRepositoryInterface_FindByLineUserID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepositoryInterface_FindByLineUserID_Call) RunAndReturn(run func(lineUserID string) (*models.User, error)) *MockUserRepositoryInterface_FindByLineUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreate provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) FindOrCreate(lineUserID string) (*models.User, bool, error) {
	ret := _mock.Called(lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 *models.User
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.User, bool, error)); ok {
		return returnFunc(lineUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = returnFunc(lineUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(lineUserID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(lineUserID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserRepositoryInterface_FindOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreate'
type MockUserRepositoryInterface_FindOrCreate_Call struct {
	*mock.Call
}

// FindOrCreate is a helper method to define mock.On call
//   - lineUserID string
func (_e *MockUserRepositoryInterface_Expecter) FindOrCreate(lineUserID any) *MockUserRepositoryInterface_FindOrCreate_Call {
	return &MockUserRepositoryInterface_FindOrCreate_Call{Call: _e.mock.On("FindOrCreate", lineUserID)}
}

func (_c *MockUserRepositoryInterface_FindOrCreate_Call) Run(run func(lineUserID string)) *MockUserRepositoryInterface_FindOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_FindOrCreate_Call) Return(user *models.User, b bool, err error) *MockUserRepositoryInterface_FindOrCreate_Call {
	_c.Call.Return(user, b, err)
	return _c
}

func (_c *MockUserRepositoryInterface_FindOrCreate_Call) RunAndReturn(run func(lineUserID string) (*models.User, bool, error)) *MockUserRepositoryInterface_FindOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) UpdateStatus(lineUserID string, status string) error {
	ret := _mock.Called(lineUserID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(lineUserID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepositoryInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockUserRepositoryInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - lineUserID string
//   - status string
func (_e *MockUserRepositoryInterface_Expecter) UpdateStatus(lineUserID any, status any) *MockUserRepositoryInterface_UpdateStatus_Call {
	return &MockUserRepositoryInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", lineUserID, status)}
}

func (_c *MockUserRepositoryInterface_UpdateStatus_Call) Run(run func(lineUserID string, status string)) *MockUserRepositoryInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_UpdateStatus_Call) Return(err error) *MockUserRepositoryInterface_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepositoryInterface_UpdateStatus_Call) RunAndReturn(run func(lineUserID string, status string) error) *MockUserRepositoryInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
