// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"lotto-journal/api/internal/models"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockDrawRepositoryInterface creates a new instance of MockDrawRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDrawRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDrawRepositoryInterface {
	mock := &MockDrawRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDrawRepositoryInterface is an autogenerated mock type for the DrawRepositoryInterface type
type MockDrawRepositoryInterface struct {
	mock.Mock
}

type MockDrawRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDrawRepositoryInterface) EXPECT() *MockDrawRepositoryInterface_Expecter {
	return &MockDrawRepositoryInterface_Expecter{mock: &_m.Mock}
}

// FindByDate provides a mock function for the type MockDrawRepositoryInterface
func (_mock *MockDrawRepositoryInterface) FindByDate(date time.Time) (*models.Draw, error) {
	ret := _mock.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for FindByDate")
	}

	var r0 *models.Draw
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) (*models.Draw, error)); ok {
		return returnFunc(date)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time) *models.Draw); ok {
		r0 = returnFunc(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Draw)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = returnFunc(date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDrawRepositoryInterface_FindByDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDate'
type MockDrawRepositoryInterface_FindByDate_Call struct {
	*mock.Call
}

// FindByDate is a helper method to define mock.On call
//   - date time.Time
func (_e *MockDrawRepositoryInterface_Expecter) FindByDate(date any) *MockDrawRepositoryInterface_FindByDate_Call {
	return &MockDrawRepositoryInterface_FindByDate_Call{Call: _e.mock.On("FindByDate", date)}
}

func (_c *MockDrawRepositoryInterface_FindByDate_Call) Run(run func(date time.Time)) *MockDrawRepositoryInterface_FindByDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDrawRepositoryInterface_FindByDate_Call) Return(draw *models.Draw, err error) *MockDrawRepositoryInterface_FindByDate_Call {
	_c.Call.Return(draw, err)
	return _c
}

func (_c *MockDrawRepositoryInterface_FindByDate_Call) RunAndReturn(run func(date time.Time) (*models.Draw, error)) *MockDrawRepositoryInterface_FindByDate_Call {
	_c.Call.Return(run)
	return _c
}

// FindLatestUnverified provides a mock function for the type MockDrawRepositoryInterface
func (_mock *MockDrawRepositoryInterface) FindLatestUnverified(date time.Time) (*models.Draw, error) {
	ret := _mock.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestUnverified")
	}

	var r0 *models.Draw
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) (*models.Draw, error)); ok {
		return returnFunc(date)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time) *models.Draw); ok {
		r0 = returnFunc(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Draw)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = returnFunc(date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDrawRepositoryInterface_FindLatestUnverified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestUnverified'
type MockDrawRepositoryInterface_FindLatestUnverified_Call struct {
	*mock.Call
}

// FindLatestUnverified is a helper method to define mock.On call
//   - date time.Time
func (_e *MockDrawRepositoryInterface_Expecter) FindLatestUnverified(date any) *MockDrawRepositoryInterface_FindLatestUnverified_Call {
	return &MockDrawRepositoryInterface_FindLatestUnverified_Call{Call: _e.mock.On("FindLatestUnverified", date)}
}

func (_c *MockDrawRepositoryInterface_FindLatestUnverified_Call) Run(run func(date time.Time)) *MockDrawRepositoryInterface_FindLatestUnverified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDrawRepositoryInterface_FindLatestUnverified_Call) Return(draw *models.Draw, err error) *MockDrawRepositoryInterface_FindLatestUnverified_Call {
	_c.Call.Return(draw, err)
	return _c
}

func (_c *MockDrawRepositoryInterface_FindLatestUnverified_Call) RunAndReturn(run func(date time.Time) (*models.Draw, error)) *MockDrawRepositoryInterface_FindLatestUnverified_Call {
	_c.Call.Return(run)
	return _c
}

// FindNextDraw provides a mock function for the type MockDrawRepositoryInterface
func (_mock *MockDrawRepositoryInterface) FindNextDraw(fromDate time.Time) (*models.Draw, error) {
	ret := _mock.Called(fromDate)

	if len(ret) == 0 {
		panic("no return value specified for FindNextDraw")
	}

	var r0 *models.Draw
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) (*models.Draw, error)); ok {
		return returnFunc(fromDate)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time) *models.Draw); ok {
		r0 = returnFunc(fromDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Draw)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = returnFunc(fromDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDrawRepositoryInterface_FindNextDraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNextDraw'
type MockDrawRepositoryInterface_FindNextDraw_Call struct {
	*mock.Call
}

// FindNextDraw is a helper method to define mock.On call
//   - fromDate time.Time
func (_e *MockDrawRepositoryInterface_Expecter) FindNextDraw(fromDate any) *MockDrawRepositoryInterface_FindNextDraw_Call {
	return &MockDrawRepositoryInterface_FindNextDraw_Call{Call: _e.mock.On("FindNextDraw", fromDate)}
}

func (_c *MockDrawRepositoryInterface_FindNextDraw_Call) Run(run func(fromDate time.Time)) *MockDrawRepositoryInterface_FindNextDraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDrawRepositoryInterface_FindNextDraw_Call) Return(draw *models.Draw, err error) *MockDrawRepositoryInterface_FindNextDraw_Call {
	_c.Call.Return(draw, err)
	return _c
}

func (_c *MockDrawRepositoryInterface_FindNextDraw_Call) RunAndReturn(run func(fromDate time.Time) (*models.Draw, error)) *MockDrawRepositoryInterface_FindNextDraw_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreate provides a mock function for the type MockDrawRepositoryInterface
func (_mock *MockDrawRepositoryInterface) FindOrCreate(date time.Time) (*models.Draw, error) {
	ret := _mock.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 *models.Draw
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) (*models.Draw, error)); ok {
		return returnFunc(date)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time) *models.Draw); ok {
		r0 = returnFunc(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Draw)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = returnFunc(date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDrawRepositoryInterface_FindOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreate'
type MockDrawRepositoryInterface_FindOrCreate_Call struct {
	*mock.Call
}

// FindOrCreate is a helper method to define mock.On call
//   - date time.Time
func (_e *MockDrawRepositoryInterface_Expecter) FindOrCreate(date any) *MockDrawRepositoryInterface_FindOrCreate_Call {
	return &MockDrawRepositoryInterface_FindOrCreate_Call{Call: _e.mock.On("FindOrCreate", date)}
}

func (_c *MockDrawRepositoryInterface_FindOrCreate_Call) Run(run func(date time.Time)) *MockDrawRepositoryInterface_FindOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDrawRepositoryInterface_FindOrCreate_Call) Return(draw *models.Draw, err error) *MockDrawRepositoryInterface_FindOrCreate_Call {
	_c.Call.Return(draw, err)
	return _c
}

func (_c *MockDrawRepositoryInterface_FindOrCreate_Call) RunAndReturn(run func(date time.Time) (*models.Draw, error)) *MockDrawRepositoryInterface_FindOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// MarkVerifiedInTransaction provides a mock function for the type MockDrawRepositoryInterface
func (_mock *MockDrawRepositoryInterface) MarkVerifiedInTransaction(tx *gorm.DB, drawID uuid.UUID) error {
	ret := _mock.Called(tx, drawID)

	if len(ret) == 0 {
		panic("no return value specified for MarkVerifiedInTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB, uuid.UUID) error); ok {
		r0 = returnFunc(tx, drawID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDrawRepositoryInterface_MarkVerifiedInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkVerifiedInTransaction'
type MockDrawRepositoryInterface_MarkVerifiedInTransaction_Call struct {
	*mock.Call
}

// MarkVerifiedInTransaction is a helper method to define mock.On call
//   - tx *gorm.DB
//   - drawID uuid.UUID
func (_e *MockDrawRepositoryInterface_Expecter) MarkVerifiedInTransaction(tx any, drawID any) *MockDrawRepositoryInterface_MarkVerifiedInTransaction_Call {
	return &MockDrawRepositoryInterface_MarkVerifiedInTransaction_Call{Call: _e.mock.On("MarkVerifiedInTransaction", tx, drawID)}
}

func (_c *MockDrawRepositoryInterface_MarkVerifiedInTransaction_Call) Run(run func(tx *gorm.DB, drawID uuid.UUID)) *MockDrawRepositoryInterface_MarkVerifiedInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDrawRepositoryInterface_MarkVerifiedInTransaction_Call) Return(err error) *MockDrawRepositoryInterface_MarkVerifiedInTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDrawRepositoryInterface_MarkVerifiedInTransaction_Call) RunAndReturn(run func(tx *gorm.DB, drawID uuid.UUID) error) *MockDrawRepositoryInterface_MarkVerifiedInTransaction_Call {
	_c.Call.Return(run)
	return _c
}
