// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationServiceInterface creates a new instance of MockNotificationServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationServiceInterface {
	mock := &MockNotificationServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationServiceInterface is an autogenerated mock type for the NotificationServiceInterface type
type MockNotificationServiceInterface struct {
	mock.Mock
}

type MockNotificationServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationServiceInterface) EXPECT() *MockNotificationServiceInterface_Expecter {
	return &MockNotificationServiceInterface_Expecter{mock: &_m.Mock}
}

// LogNotification provides a mock function for the type MockNotificationServiceInterface
func (_mock *MockNotificationServiceInterface) LogNotification(userID uuid.UUID, lineUserID string, notifType string, drawID *uuid.UUID, status string, errStr *string) error {
	ret := _mock.Called(userID, lineUserID, notifType, drawID, status, errStr)

	if len(ret) == 0 {
		panic("no return value specified for LogNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string, string, *uuid.UUID, string, *string) error); ok {
		r0 = returnFunc(userID, lineUserID, notifType, drawID, status, errStr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationServiceInterface_LogNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogNotification'
type MockNotificationServiceInterface_LogNotification_Call struct {
	*mock.Call
}

// LogNotification is a helper method to define mock.On call
//   - userID uuid.UUID
//   - lineUserID string
//   - notifType string
//   - drawID *uuid.UUID
//   - status string
//   - errStr *string
func (_e *MockNotificationServiceInterface_Expecter) LogNotification(userID any, lineUserID any, notifType any, drawID any, status any, errStr any) *MockNotificationServiceInterface_LogNotification_Call {
	return &MockNotificationServiceInterface_LogNotification_Call{Call: _e.mock.On("LogNotification", userID, lineUserID, notifType, drawID, status, errStr)}
}

func (_c *MockNotificationServiceInterface_LogNotification_Call) Run(run func(userID uuid.UUID, lineUserID string, notifType string, drawID *uuid.UUID, status string, errStr *string)) *MockNotificationServiceInterface_LogNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockNotificationServiceInterface_LogNotification_Call) Return(err error) *MockNotificationServiceInterface_LogNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationServiceInterface_LogNotification_Call) RunAndReturn(run func(userID uuid.UUID, lineUserID string, notifType string, drawID *uuid.UUID, status string, errStr *string) error) *MockNotificationServiceInterface_LogNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendDrawNotifications provides a mock function for the type MockNotificationServiceInterface
func (_mock *MockNotificationServiceInterface) SendDrawNotifications(ctx context.Context, drawID uuid.UUID, drawDateStr string) error {
	ret := _mock.Called(ctx, drawID, drawDateStr)

	if len(ret) == 0 {
		panic("no return value specified for SendDrawNotifications")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, drawID, drawDateStr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationServiceInterface_SendDrawNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDrawNotifications'
type MockNotificationServiceInterface_SendDrawNotifications_Call struct {
	*mock.Call
}

// SendDrawNotifications is a helper method to define mock.On call
//   - ctx context.Context
//   - drawID uuid.UUID
//   - drawDateStr string
func (_e *MockNotificationServiceInterface_Expecter) SendDrawNotifications(ctx any, drawID any, drawDateStr any) *MockNotificationServiceInterface_SendDrawNotifications_Call {
	return &MockNotificationServiceInterface_SendDrawNotifications_Call{Call: _e.mock.On("SendDrawNotifications", ctx, drawID, drawDateStr)}
}

func (_c *MockNotificationServiceInterface_SendDrawNotifications_Call) Run(run func(ctx context.Context, drawID uuid.UUID, drawDateStr string)) *MockNotificationServiceInterface_SendDrawNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationServiceInterface_SendDrawNotifications_Call) Return(err error) *MockNotificationServiceInterface_SendDrawNotifications_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationServiceInterface_SendDrawNotifications_Call) RunAndReturn(run func(ctx context.Context, drawID uuid.UUID, drawDateStr string) error) *MockNotificationServiceInterface_SendDrawNotifications_Call {
	_c.Call.Return(run)
	return _c
}
