// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"lotto-journal/api/internal/models"
	"lotto-journal/api/internal/service"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTicketServiceInterface creates a new instance of MockTicketServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketServiceInterface {
	mock := &MockTicketServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTicketServiceInterface is an autogenerated mock type for the TicketServiceInterface type
type MockTicketServiceInterface struct {
	mock.Mock
}

type MockTicketServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketServiceInterface) EXPECT() *MockTicketServiceInterface_Expecter {
	return &MockTicketServiceInterface_Expecter{mock: &_m.Mock}
}

// ListTickets provides a mock function for the type MockTicketServiceInterface
func (_mock *MockTicketServiceInterface) ListTickets(ownerID uuid.UUID) ([]*models.Ticket, time.Time, error) {
	ret := _mock.Called(ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListTickets")
	}

	var r0 []*models.Ticket
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]*models.Ticket, time.Time, error)); ok {
		return returnFunc(ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []*models.Ticket); ok {
		r0 = returnFunc(ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) time.Time); ok {
		r1 = returnFunc(ownerID)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(uuid.UUID) error); ok {
		r2 = returnFunc(ownerID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTicketServiceInterface_ListTickets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTickets'
type MockTicketServiceInterface_ListTickets_Call struct {
	*mock.Call
}

// ListTickets is a helper method to define mock.On call
//   - ownerID uuid.UUID
func (_e *MockTicketServiceInterface_Expecter) ListTickets(ownerID any) *MockTicketServiceInterface_ListTickets_Call {
	return &MockTicketServiceInterface_ListTickets_Call{Call: _e.mock.On("ListTickets", ownerID)}
}

func (_c *MockTicketServiceInterface_ListTickets_Call) Run(run func(ownerID uuid.UUID)) *MockTicketServiceInterface_ListTickets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTicketServiceInterface_ListTickets_Call) Return(tickets []*models.Ticket, time1 time.Time, err error) *MockTicketServiceInterface_ListTickets_Call {
	_c.Call.Return(tickets, time1, err)
	return _c
}

func (_c *MockTicketServiceInterface_ListTickets_Call) RunAndReturn(run func(ownerID uuid.UUID) ([]*models.Ticket, time.Time, error)) *MockTicketServiceInterface_ListTickets_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitTickets provides a mock function for the type MockTicketServiceInterface
func (_mock *MockTicketServiceInterface) SubmitTickets(ownerID uuid.UUID, text string) ([]service.ParsedTicket, []string, uuid.UUID, error) {
	ret := _mock.Called(ownerID, text)

	if len(ret) == 0 {
		panic("no return value specified for SubmitTickets")
	}

	var r0 []service.ParsedTicket
	var r1 []string
	var r2 uuid.UUID
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string) ([]service.ParsedTicket, []string, uuid.UUID, error)); ok {
		return returnFunc(ownerID, text)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string) []service.ParsedTicket); ok {
		r0 = returnFunc(ownerID, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.ParsedTicket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, string) []string); ok {
		r1 = returnFunc(ownerID, text)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(uuid.UUID, string) uuid.UUID); ok {
		r2 = returnFunc(ownerID, text)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(uuid.UUID, string) error); ok {
		r3 = returnFunc(ownerID, text)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockTicketServiceInterface_SubmitTickets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitTickets'
type MockTicketServiceInterface_SubmitTickets_Call struct {
	*mock.Call
}

// SubmitTickets is a helper method to define mock.On call
//   - ownerID uuid.UUID
//   - text string
func (_e *MockTicketServiceInterface_Expecter) SubmitTickets(ownerID any, text any) *MockTicketServiceInterface_SubmitTickets_Call {
	return &MockTicketServiceInterface_SubmitTickets_Call{Call: _e.mock.On("SubmitTickets", ownerID, text)}
}

func (_c *MockTicketServiceInterface_SubmitTickets_Call) Run(run func(ownerID uuid.UUID, text string)) *MockTicketServiceInterface_SubmitTickets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTicketServiceInterface_SubmitTickets_Call) Return(parsedTickets []service.ParsedTicket, strings []string, uUID uuid.UUID, err error) *MockTicketServiceInterface_SubmitTickets_Call {
	_c.Call.Return(parsedTickets, strings, uUID, err)
	return _c
}

func (_c *MockTicketServiceInterface_SubmitTickets_Call) RunAndReturn(run func(ownerID uuid.UUID, text string) ([]service.ParsedTicket, []string, uuid.UUID, error)) *MockTicketServiceInterface_SubmitTickets_Call {
	_c.Call.Return(run)
	return _c
}
