// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "lotto-journal/api/internal/models"

	mock "github.com/stretchr/testify/mock"

	service "lotto-journal/api/internal/service"

	uuid "github.com/google/uuid"
)

// TicketServiceInterface is an autogenerated mock type for the TicketServiceInterface type
type TicketServiceInterface struct {
	mock.Mock
}

// ListTickets provides a mock function with given fields: ownerID
func (_m *TicketServiceInterface) ListTickets(ownerID uuid.UUID) ([]*models.Ticket, error) {
	ret := _m.Called(ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListTickets")
	}

	var r0 []*models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]*models.Ticket, error)); ok {
		return rf(ownerID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []*models.Ticket); ok {
		r0 = rf(ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitTickets provides a mock function with given fields: ownerID, text
func (_m *TicketServiceInterface) SubmitTickets(ownerID uuid.UUID, text string) ([]service.ParsedTicket, []string, error) {
	ret := _m.Called(ownerID, text)

	if len(ret) == 0 {
		panic("no return value specified for SubmitTickets")
	}

	var r0 []service.ParsedTicket
	var r1 []string
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) ([]service.ParsedTicket, []string, error)); ok {
		return rf(ownerID, text)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) []service.ParsedTicket); ok {
		r0 = rf(ownerID, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.ParsedTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) []string); ok {
		r1 = rf(ownerID, text)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, string) error); ok {
		r2 = rf(ownerID, text)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewTicketServiceInterface creates a new instance of TicketServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketServiceInterface {
	mock := &TicketServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
