// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "lotto-journal/api/internal/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	uuid "github.com/google/uuid"
)

// TicketRepositoryInterface is an autogenerated mock type for the TicketRepositoryInterface type
type TicketRepositoryInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ticket
func (_m *TicketRepositoryInterface) Create(ticket *models.Ticket) error {
	ret := _m.Called(ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Ticket) error); ok {
		r0 = rf(ticket)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUnchecked provides a mock function with given fields: drawID
func (_m *TicketRepositoryInterface) FindUnchecked(drawID uuid.UUID) ([]*models.Ticket, error) {
	ret := _m.Called(drawID)

	if len(ret) == 0 {
		panic("no return value specified for FindUnchecked")
	}

	var r0 []*models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]*models.Ticket, error)); ok {
		return rf(drawID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []*models.Ticket); ok {
		r0 = rf(drawID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(drawID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: drawID, userID
func (_m *TicketRepositoryInterface) List(drawID uuid.UUID, userID uuid.UUID) ([]*models.Ticket, error) {
	ret := _m.Called(drawID, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) ([]*models.Ticket, error)); ok {
		return rf(drawID, userID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) []*models.Ticket); ok {
		r0 = rf(drawID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(drawID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkCheckedInTransaction provides a mock function with given fields: tx, ticketIDs
func (_m *TicketRepositoryInterface) MarkCheckedInTransaction(tx *gorm.DB, ticketIDs []uuid.UUID) error {
	ret := _m.Called(tx, ticketIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkCheckedInTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, []uuid.UUID) error); ok {
		r0 = rf(tx, ticketIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTicketRepositoryInterface creates a new instance of TicketRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketRepositoryInterface {
	mock := &TicketRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
