// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "lotto-journal/api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// UserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type UserRepositoryInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: user
func (_m *UserRepositoryInterface) Create(user *models.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByLineUserID provides a mock function with given fields: lineUserID
func (_m *UserRepositoryInterface) FindByLineUserID(lineUserID string) (*models.User, error) {
	ret := _m.Called(lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindByLineUserID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.User, error)); ok {
		return rf(lineUserID)
	}
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(lineUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(lineUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOrCreate provides a mock function with given fields: lineUserID
func (_m *UserRepositoryInterface) FindOrCreate(lineUserID string) (*models.User, bool, error) {
	ret := _m.Called(lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 *models.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (*models.User, bool, error)); ok {
		return rf(lineUserID)
	}
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(lineUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(lineUserID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(lineUserID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateStatus provides a mock function with given fields: lineUserID, status
func (_m *UserRepositoryInterface) UpdateStatus(lineUserID string, status string) error {
	ret := _m.Called(lineUserID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(lineUserID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepositoryInterface creates a new instance of UserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryInterface {
	mock := &UserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
