// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "lotto-journal/api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// UserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type UserServiceInterface struct {
	mock.Mock
}

// Deactivate provides a mock function with given fields: lineUserID
func (_m *UserServiceInterface) Deactivate(lineUserID string) error {
	ret := _m.Called(lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(lineUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOrCreate provides a mock function with given fields: lineUserID
func (_m *UserServiceInterface) FindOrCreate(lineUserID string) (*models.User, bool, error) {
	ret := _m.Called(lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 *models.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (*models.User, bool, error)); ok {
		return rf(lineUserID)
	}
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(lineUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(lineUserID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(lineUserID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Reactivate provides a mock function with given fields: lineUserID
func (_m *UserServiceInterface) Reactivate(lineUserID string) error {
	ret := _m.Called(lineUserID)

	if len(ret) == 0 {
		panic("no return value specified for Reactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(lineUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserServiceInterface creates a new instance of UserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceInterface {
	mock := &UserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
