all: true
dir: 'internal/mocks'
force-file-write: true
structname: 'Mock{{.InterfaceName}}'
pkgname: 'mocks'
filename: 'Mock{{.InterfaceName}}.go'
packages:
  lotto-journal/api/internal/service:
  lotto-journal/api/internal/repository:
